"""
테이블 생성 스크립트
"""
import pymysql
import os
from dotenv import load_dotenv

load_dotenv()

conn = pymysql.connect(
    host=os.getenv("MYSQL_HOST"),
    user=os.getenv("MYSQL_USER"),
    password=os.getenv("MYSQL_PASSWORD"),
    database=os.getenv("MYSQL_DB"),
    port=int(os.getenv("MYSQL_PORT", 3306))
)

cursor = conn.cursor()

# 1. APP_API_ROUTE_L
sql1 = """
CREATE TABLE IF NOT EXISTS APP_API_ROUTE_L (
    ROUTE_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    API_PATH VARCHAR(255) NOT NULL,
    HTTP_MTHD VARCHAR(10) NOT NULL,
    API_NAME VARCHAR(255) NULL,
    API_DESC TEXT NULL,
    TAGS VARCHAR(500) NULL,
    USE_YN CHAR(1) NOT NULL DEFAULT 'Y',
    DEL_YN CHAR(1) NOT NULL DEFAULT 'N',
    AUTH_YN CHAR(1) NOT NULL DEFAULT 'N',
    ALWD_ORGNS TEXT NULL,
    RATE_LMT VARCHAR(10) DEFAULT '100',
    CREA_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_DT TIMESTAMP NULL,
    CREA_BY VARCHAR(100) NULL,
    UPDT_BY VARCHAR(100) NULL,
    INDEX IDX_API_ROUTE_PATH_MTHD (API_PATH, HTTP_MTHD),
    INDEX IDX_API_ROUTE_USE_YN (USE_YN),
    INDEX IDX_API_ROUTE_DEL_YN (DEL_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
"""
cursor.execute(sql1)
print("✅ APP_API_ROUTE_L 테이블 생성 완료")

# 2. APP_API_VERSION_H
sql2 = """
CREATE TABLE IF NOT EXISTS APP_API_VERSION_H (
    VERSION_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    ROUTE_ID VARCHAR(50) NOT NULL,
    VERSION_NO INT NOT NULL,
    CRNT_YN CHAR(1) NOT NULL DEFAULT 'Y',
    REQ_SPEC JSON NULL,
    LOGIC_TYPE VARCHAR(50) NOT NULL DEFAULT 'SQL',
    LOGIC_BODY TEXT NOT NULL,
    LOGIC_CFG JSON NULL,
    RESP_SPEC JSON NULL,
    STATUS_CDS JSON NULL,
    CHG_NOTE TEXT NULL,
    CREA_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREA_BY VARCHAR(100) NULL,
    CONSTRAINT FK_API_VERSION_ROUTE FOREIGN KEY (ROUTE_ID) 
        REFERENCES APP_API_ROUTE_L(ROUTE_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    INDEX IDX_API_VERSION_ROUTE (ROUTE_ID, VERSION_NO),
    INDEX IDX_API_VERSION_CRNT (ROUTE_ID, CRNT_YN),
    UNIQUE KEY UK_ROUTE_VERSION (ROUTE_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
"""
cursor.execute(sql2)
print("✅ APP_API_VERSION_H 테이블 생성 완료")

# 3. APP_API_AUDIT_H
sql3 = """
CREATE TABLE IF NOT EXISTS APP_API_AUDIT_H (
    AUDIT_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    TRGT_TYPE VARCHAR(50) NOT NULL,
    TRGT_ID VARCHAR(50) NOT NULL,
    ACTION VARCHAR(50) NOT NULL,
    OLD_VAL JSON NULL,
    NEW_VAL JSON NULL,
    `DESC` TEXT NULL,
    ACTOR VARCHAR(100) NULL,
    ACTOR_IP VARCHAR(45) NULL,
    CREA_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_API_AUDIT_TRGT (TRGT_TYPE, TRGT_ID),
    INDEX IDX_API_AUDIT_ACTION (ACTION),
    INDEX IDX_API_AUDIT_CREA_DT (CREA_DT),
    INDEX IDX_API_AUDIT_ACTOR (ACTOR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
"""
cursor.execute(sql3)
print("✅ APP_API_AUDIT_H 테이블 생성 완료")

conn.commit()

# 테이블 확인
cursor.execute("SHOW TABLES LIKE 'APP_API%'")
print("\n📋 생성된 테이블:")
for t in cursor.fetchall():
    print(f"  - {t[0]}")

conn.close()
print("\n🎉 모든 테이블 생성 완료!")

